<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Mapping nama produk → Cloudinary public_id (filename)
     * URL base: https://res.cloudinary.com/dppeuggus/image/upload/v1775452XXX/
     */
    private function getCloudinaryMap(): array
    {
        $base = 'https://res.cloudinary.com/dppeuggus/image/upload';

        return [
            'Dipan kayu jati' => $base . '/v1775452597/DipanKayuJati_gi9jrm.jpg',
            'Backdrop' => $base . '/v1775550009/Backdrop_zlzkfr.png',
            'Meja rias' => $base . '/v1775452646/MejaRias_dhuzy4.jpg',
            'Meja rias minimalis' => $base . '/v1775452650/MejaRiasMinimalis_i5v5p1.jpg',
            'Rak sepatu' => $base . '/v1775550012/RakSepatu_1_d1s2if.png',
            'Meja makan' => $base . '/v1775452627/MejaMakan_nia7mr.jpg',
            'Nakas Mindi' => $base . '/v1775452671/NakasMindi_t4hyn4.jpg',
            'Meja makan besar' => $base . '/v1775452628/MejaMakanBesar_a71ucd.jpg',
            'Ayunan 2 dudukan' => $base . '/v1775452590/Ayunan2Dudukan_lcreoi.jpg',
            'Gazebo' => $base . '/v1775452600/Gazebo_ygwpwc.jpg',
            'Meja roda dan kursi' => $base . '/v1775452656/MejaRodaDanKursi_oq2trz.jpg',
            'Meja roda' => $base . '/v1775452653/MejaRoda_rz71jk.jpg',
            'Bangku roda belakang' => $base . '/v1775452594/BangkuRodaBelakang_jhgog7.jpg',
            'Rak ranting' => $base . '/v1775452671/RakRanting_l4ari5.jpg',
            'Bangku kayu bulat' => $base . '/v1775452590/BangkuBulat_zlknuo.jpg',
            'Stole' => $base . '/v1775452676/Stole_mpv4pq.jpg',
            'Meja makan ranting' => $base . '/v1775452630/MejaMakanRanting_snq3v2.jpg',
            'Gazebo kecil' => $base . '/v1775452602/GazeboKecil_nneuhl.jpg',
            'Meja makan ukir bulat' => $base . '/v1775452638/MejaMakanUkirBulat_gbgigj.jpg',
            'Meja makan ukir persegi' => $base . '/v1775452640/MejaMakanUkirPersegi_ruvry2.jpg',
            'Bangku roda' => $base . '/v1775452593/BangkuRoda_jfy5yb.jpg',
            'Kursi kayu bulat satu set' => $base . '/v1775452603/KursiKayuBulatSatuSet_ecir3h.jpg',
            'Kursi makan bulat ranting' => $base . '/v1775550009/KursiMakanBulatRanting_wtdvyx.png',
            'Kursi makan jari jari satu set' => $base . '/v1775452606/KursiMakanJariJariSatuSet_yh4egm.jpg',
            'Kursi roda tamu' => $base . '/v1775452610/KursiRodaTamu_vea1og.jpg',
            'Kursi makan ukir' => $base . '/v1775550008/KursiMakanUkir_mlez4t.png',
            'Kursi sofa bulat' => $base . '/v1775452613/KursiSofaPersegi_zflioa.jpg',
            'Meja roda hias' => $base . '/v1775452659/MejaRodaHias_t2kfix.jpg',
            'Bangku sofa rantai' => $base . '/v1775452596/BangkuSofaRantai_jajkpa.jpg',
            'Kursi makan belakang roda' => $base . '/v1775452604/KursiMakanBelakangRoda_a9lwvj.jpg',
            'Setol' => $base . '/v1775452675/Setol_rcc00y.jpg',
            'Meja makan senderan jari 4' => $base . '/v1775452635/MejaMakanSenderanJari4_laan4q.jpg',
            'Rak ranting pintu 2' => $base . '/v1775550009/RakRantingPintu2_ynudli.png',
            'Meja ranting akar bulat' => $base . '/v1775550015/MejaRantingAkarBulat_yi5rpw.png',
            'Meja roda kursi' => $base . '/v1775452626/MejaKursiRoda_pxzvjk.jpg',
            'Meja sudut roda' => $base . '/v1775452665/MejaSudutRoda_prftdm.webp',
            'Nakas laci 8' => $base . '/v1775452668/Nakas_dcxzav.jpg',
            'Dipan ranting' => $base . '/v1775452599/DipanRanting_ynrf9q.jpg',
            'Dipan mini' => $base . '/v1775550008/DipanMini_bsspew.png',
            'Bangku gambangan ranting' => $base . '/v1775452591/BangkuGambanganRanting_cbibsq.jpg',
            'Meja makan roda bulat' => $base . '/v1775550010/MejaMakanRodaBulat_jx4lb1.png',
            'Meja roda penghias halaman' => $base . '/v1775452661/MejaRodaPenghiasHalaman_cshtrf.jpg',
            'Bangku kaki roda' => $base . '/v1775452592/BangkuKakiRoda_pikmlf.jpg',
            'Lemari pakaian' => $base . '/v1775452618/LemariPakaian_u03zsm.jpg',
            'Lemari 3 pintu' => $base . '/v1775550011/Lemari3Pintu_cek354.png',
            'Lemari sudut' => $base . '/v1775452620/LemariSudut_qr82cd.jpg',
            'Lemari 3 pintu klasik' => $base . '/v1775452617/Lemari3PintuKlasik_hy2svd.jpg',
            'Meja betawi' => $base . '/v1775452625/MejaBetawi_c2tzcb.jpg',
            'Meja bakso' => $base . '/v1775452623/MejaBakso_qbsecg.jpg',
            'Kursi tamu betawi' => $base . '/v1775550010/KursiTamuBetawi_i0wsoq.png',
            'Lonjer' => $base . '/v1775452621/Lonjer_zg59dw.jpg',
            'Meja belajar' => $base . '/v1775452624/MejaBelajar_a1chk4.jpg',
            'Kursi dudukan lengkung' => $base . '/v1775550008/KursiDudukanLengkung_rnqoyt.png',
            'Meja ranting laci' => $base . '/v1775455217/MejaRantingLaci_u2xjom.jpg',
        ];
    }

    public function run(): void
    {
        // Ambil mapping kategori & jenis kayu berdasarkan nama
        $categories = DB::table('categories')->pluck('id', 'nama');
        $woodTypes = DB::table('wood_types')->pluck('id', 'nama');

        // Cloudinary image mapping
        $cloudinaryMap = $this->getCloudinaryMap();

        $products = [
            [
                'nama_produk' => 'Dipan kayu jati',
                'kategori' => 'Dipan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 4300000,
                'deskripsi' => 'Dipan tidur berkualitas tinggi yang terbuat dari kayu jati solid, dikenal tahan lama dan kokoh.',
                'berat' => 50,
            ],
            [
                'nama_produk' => 'Backdrop',
                'kategori' => 'Backdrop',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 5200000,
                'deskripsi' => 'Backdrop dekoratif berbahan kayu jati yang kuat dan tahan lama, cocok untuk memperindah tampilan ruangan atau latar belakang acara.',
                'berat' => 120,
            ],
            [
                'nama_produk' => 'Lemari pakaian',
                'kategori' => 'Lemari',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 6200000,
                'deskripsi' => 'Lemari pakaian elegan berbahan kayu jati solid, dirancang dengan desain klasik yang kokoh dan tahan lama. Menyediakan ruang penyimpanan luas untuk pakaian dan perlengkapan lainnya.',
                'berat' => 80,
            ],
            [
                'nama_produk' => 'Meja rias',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Meja rias klasik berbahan kayu jati solid dengan tampilan elegan dan fungsional. Dilengkapi ruang penyimpanan yang praktis untuk perlengkapan rias.',
                'berat' => 30,
            ],
            [
                'nama_produk' => 'Meja rias minimalis',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1790000,
                'deskripsi' => 'Meja rias bergaya minimalis dengan material kayu jati yang kokoh dan tahan lama. Desain simpel namun elegan, ideal untuk mempercantik ruang tidur Anda.',
                'berat' => 30,
            ],
            [
                'nama_produk' => 'Rak sepatu',
                'kategori' => 'Rak',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1200000,
                'deskripsi' => 'Rak sepatu dari kayu jati yang kuat dan tahan lama, dengan desain sederhana namun elegan. Cocok untuk menjaga kerapihan dan menambah estetika ruangan.',
                'berat' => 20,
            ],
            [
                'nama_produk' => 'Lemari 3 pintu',
                'kategori' => 'Lemari',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 4500000,
                'deskripsi' => 'Lemari pakaian dengan tiga pintu berbahan kayu jati yang kokoh dan tahan lama. Menyediakan ruang penyimpanan luas, ideal untuk kebutuhan keluarga.',
                'berat' => 120,
            ],
            [
                'nama_produk' => 'Meja makan',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Meja makan berbahan kayu jati yang kokoh dan tahan lama, dengan desain elegan yang cocok untuk ruang makan keluarga.',
                'berat' => 80,
            ],
            [
                'nama_produk' => 'Lemari sudut',
                'kategori' => 'Lemari',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Desainnya efisien untuk memaksimalkan ruang penyimpanan di sudut ruangan.',
                'berat' => 65,
            ],
            [
                'nama_produk' => 'Nakas Mindi',
                'kategori' => 'Nakas',
                'jenis_kayu' => 'Kayu Mindi',
                'harga' => 1800000,
                'deskripsi' => 'Cocok sebagai meja samping tempat tidur atau ruang tamu.',
                'berat' => 50,
            ],
            [
                'nama_produk' => 'Meja makan besar',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3000000,
                'deskripsi' => 'Ideal untuk menciptakan suasana hangat dan nyaman saat bersantap bersama keluarga.',
                'berat' => 90,
            ],
            [
                'nama_produk' => 'Lemari 3 pintu klasik',
                'kategori' => 'Lemari',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 4300000,
                'deskripsi' => 'Desain klasik dengan ruang penyimpanan luas, cocok untuk menata pakaian dan perlengkapan Anda.',
                'berat' => 110,
            ],
            [
                'nama_produk' => 'Ayunan 2 dudukan',
                'kategori' => 'Ayunan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Dirancang untuk dua orang dengan kekuatan dan daya tahan tinggi. Cocok untuk bersantai di teras atau taman rumah.',
                'berat' => 90,
            ],
            [
                'nama_produk' => 'Gazebo',
                'kategori' => 'Gazebo',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3500000,
                'deskripsi' => 'Cocok untuk area taman atau halaman, memberikan suasana santai dan alami.',
                'berat' => 150,
            ],
            [
                'nama_produk' => 'Meja roda dan kursi',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Kembang',
                'harga' => 2500000,
                'deskripsi' => 'Cocok untuk ruang tamu atau ruang kerja yang stylish.',
                'berat' => 170,
            ],
            [
                'nama_produk' => 'Meja roda',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2000000,
                'deskripsi' => 'Meja roda praktis terbuat dari kayu jati berkualitas, kokoh dan mudah dipindahkan berkat roda yang terpasang. Ideal untuk ruang kerja atau ruang tamu.',
                'berat' => 70,
            ],
            [
                'nama_produk' => 'Meja betawi',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Desain tradisional dengan sentuhan elegan, cocok untuk ruang makan atau ruang tamu.',
                'berat' => 160,
            ],
            [
                'nama_produk' => 'Bangku roda belakang',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1500000,
                'deskripsi' => 'Desain praktis dan tahan lama, cocok untuk berbagai kebutuhan tempat duduk.',
                'berat' => 70,
            ],
            [
                'nama_produk' => 'Rak ranting',
                'kategori' => 'Rak',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1300000,
                'deskripsi' => 'Rak unik berbahan kayu jati dengan desain menyerupai ranting pohon, memberikan sentuhan natural dan artistik pada ruangan. Cocok untuk menyimpan barang atau sebagai dekorasi.',
                'berat' => 75,
            ],
            [
                'nama_produk' => 'Bangku kayu bulat',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1300000,
                'deskripsi' => 'Desainnya simpel dengan permukaan dudukan berbentuk lingkaran, cocok digunakan di ruang tamu, teras, atau kafe bergaya alami.',
                'berat' => 80,
            ],
            [
                'nama_produk' => 'Stole',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1100000,
                'deskripsi' => 'Ideal sebagai pelengkap meja atau tempat duduk tambahan. Terbuat dari kayu jati yang kuat dan awet, cocok digunakan di ruang makan, dapur, atau area santai.',
                'berat' => 90,
            ],
            [
                'nama_produk' => 'Meja makan ranting',
                'kategori' => 'Meja Makan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2200000,
                'deskripsi' => 'Meja ini cocok untuk ruang makan bergaya rustic atau natural. Kuat, tahan lama, dan bernilai estetika tinggi.',
                'berat' => 170,
            ],
            [
                'nama_produk' => 'Gazebo kecil',
                'kategori' => 'Gazebo',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2700000,
                'deskripsi' => 'Dirancang untuk menciptakan ruang santai di taman atau halaman rumah.',
                'berat' => 130,
            ],
            [
                'nama_produk' => 'Meja makan ukir bulat',
                'kategori' => 'Meja Makan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2400000,
                'deskripsi' => 'Meja makan berbentuk bulat dengan ukiran khas pada bagian kaki dan tepi.',
                'berat' => 170,
            ],
            [
                'nama_produk' => 'Meja makan ukir persegi',
                'kategori' => 'Meja Makan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3800000,
                'deskripsi' => 'Terbuat dari kayu jati solid yang awet dan tahan lama, sangat cocok untuk ruang makan bergaya klasik maupun tradisional.',
                'berat' => 330,
            ],
            [
                'nama_produk' => 'Bangku roda',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2200000,
                'deskripsi' => 'Bangku ini cocok untuk taman, teras, atau sudut dekoratif dengan nuansa vintage dan alami.',
                'berat' => 135,
            ],
            [
                'nama_produk' => 'Kursi kayu bulat satu set',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2200000,
                'deskripsi' => 'Set ini cocok untuk ruang tamu, teras, atau area santai.',
                'berat' => 140,
            ],
            [
                'nama_produk' => 'Kursi makan bulat ranting',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3300000,
                'deskripsi' => 'Menghadirkan sentuhan artistik dan nuansa alami, cocok untuk ruang makan bergaya rustic atau natural.',
                'berat' => 190,
            ],
            [
                'nama_produk' => 'Meja bakso',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1900000,
                'deskripsi' => 'Dirancang dengan ukuran dan bentuk praktis untuk memudahkan penyajian dan aktivitas penjual.',
                'berat' => 110,
            ],
            [
                'nama_produk' => 'Kursi makan jari jari satu set',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2400000,
                'deskripsi' => 'Satu set kursi makan kayu jati dengan desain sandaran berupa jari-jari vertikal yang klasik dan elegan.',
                'berat' => 110,
            ],
            [
                'nama_produk' => 'Kursi roda tamu',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2700000,
                'deskripsi' => 'Kombinasi estetika klasik dan fungsi praktis, cocok untuk ruang tamu dengan nuansa tradisional yang nyaman dan elegan.',
                'berat' => 155,
            ],
            [
                'nama_produk' => 'Kursi makan ukir',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2400000,
                'deskripsi' => 'Kursi makan kayu jati dengan ornamen ukiran detail pada sandaran dan kaki, menampilkan keindahan seni tradisional.',
                'berat' => 140,
            ],
            [
                'nama_produk' => 'Kursi tamu betawi',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2600000,
                'deskripsi' => 'Desainnya elegan dan artistik, cocok untuk ruang tamu dengan nuansa etnik dan klasik. Kuat, awet, serta bernilai estetika tinggi.',
                'berat' => 190,
            ],
            [
                'nama_produk' => 'Lonjer',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1200000,
                'deskripsi' => 'Desainnya simpel dan fungsional, cocok untuk digunakan di ruang makan, teras, atau ruang bersama sebagai tempat duduk yang nyaman dan praktis.',
                'berat' => 65,
            ],
            [
                'nama_produk' => 'Kursi sofa bulat',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2700000,
                'deskripsi' => 'Cocok untuk ruang tamu atau area santai yang mengutamakan gaya dan kehangatan alami kayu jati.',
                'berat' => 115,
            ],
            [
                'nama_produk' => 'Meja roda hias',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1900000,
                'deskripsi' => 'Cocok digunakan sebagai meja dekorasi di ruang tamu atau sudut rumah.',
                'berat' => 105,
            ],
            [
                'nama_produk' => 'Bangku sofa rantai',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1700000,
                'deskripsi' => 'Bangku sofa kayu jati dengan desain unik yang menggabungkan elemen rantai sebagai penyangga atau dekorasi. Memberikan sentuhan artistik dan industrial sekaligus nuansa alami kayu jati yang kuat dan tahan lama.',
                'berat' => 70,
            ],
            [
                'nama_produk' => 'Kursi makan belakang roda',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2700000,
                'deskripsi' => 'Cocok untuk ruang makan yang mengutamakan kenyamanan dan fleksibilitas tanpa mengorbankan estetika alami kayu jati.',
                'berat' => 135,
            ],
            [
                'nama_produk' => 'Meja belajar',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1700000,
                'deskripsi' => 'Desainnya simpel dan fungsional, cocok untuk kamar belajar atau ruang kerja dengan nuansa alami dan elegan.',
                'berat' => 150,
            ],
            [
                'nama_produk' => 'Setol',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 300000,
                'deskripsi' => 'Cocok digunakan sebagai tempat duduk tambahan atau bangku kecil di berbagai ruangan.',
                'berat' => null,
            ],
            [
                'nama_produk' => 'Meja makan senderan jari 4',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2700000,
                'deskripsi' => 'Desain ini memberikan kesan klasik dan elegan, sekaligus memastikan kenyamanan saat duduk.',
                'berat' => 140,
            ],
            [
                'nama_produk' => 'Rak ranting pintu 2',
                'kategori' => 'Rak',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 900000,
                'deskripsi' => 'Cocok untuk penyimpanan barang dengan sentuhan estetika rustic dan natural.',
                'berat' => 90,
            ],
            [
                'nama_produk' => 'Meja ranting akar bulat',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 700000,
                'deskripsi' => 'Menampilkan kesan alami dan artistik, cocok untuk ruang tamu atau area santai.',
                'berat' => 30,
            ],
            [
                'nama_produk' => 'Kursi dudukan lengkung',
                'kategori' => 'Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 1600000,
                'deskripsi' => 'Bentuk lengkung memberikan dukungan optimal dan tampilan elegan, cocok untuk ruang tamu atau ruang makan dengan gaya klasik maupun modern.',
                'berat' => 75,
            ],
            [
                'nama_produk' => 'Meja roda kursi',
                'kategori' => 'Meja Kursi',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3500000,
                'deskripsi' => 'Desain praktis dan fungsional, cocok untuk ruang belajar, ruang tamu, atau ruang makan.',
                'berat' => 170,
            ],
            [
                'nama_produk' => 'Meja ranting laci',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 400000,
                'deskripsi' => 'Meja kayu jati dengan desain natural yang menampilkan motif ranting dan dilengkapi laci untuk penyimpanan tambahan.',
                'berat' => 35,
            ],
            [
                'nama_produk' => 'Meja sudut roda',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 600000,
                'deskripsi' => 'Desain praktis dan fungsional ini cocok untuk ruang tamu, ruang kerja, atau sudut ruangan.',
                'berat' => 25,
            ],
            [
                'nama_produk' => 'Nakas laci 8',
                'kategori' => 'Nakas',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 4000000,
                'deskripsi' => 'Nakas kayu jati dengan delapan laci penyimpanan yang luas dan terorganisir, ideal untuk menyimpan barang-barang kecil di kamar tidur atau ruang keluarga.',
                'berat' => 125,
            ],
            [
                'nama_produk' => 'Dipan ranting',
                'kategori' => 'Dipan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3200000,
                'deskripsi' => 'Dipan kayu jati dengan desain unik yang menonjolkan motif ranting alami pada rangka atau kaki dipan. Menghadirkan kesan rustic dan artistik.',
                'berat' => 110,
            ],
            [
                'nama_produk' => 'Dipan mini',
                'kategori' => 'Dipan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Ideal untuk kamar tidur dengan ruang terbatas atau sebagai tempat tidur tambahan.',
                'berat' => 90,
            ],
            [
                'nama_produk' => 'Bangku gambangan ranting',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 800000,
                'deskripsi' => 'Bangku kayu jati dengan desain gambangan yang menonjolkan motif ranting alami sebagai bagian dari struktur atau dekorasi.',
                'berat' => 30,
            ],
            [
                'nama_produk' => 'Meja makan roda bulat',
                'kategori' => 'Meja Makan',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2900000,
                'deskripsi' => 'Desain elegan dengan sentuhan alami kayu jati, cocok untuk ruang makan.',
                'berat' => 110,
            ],
            [
                'nama_produk' => 'Meja roda penghias halaman',
                'kategori' => 'Meja',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 3500000,
                'deskripsi' => 'Desain meja dihiasi payung yang bagus di taruh di depan rumah.',
                'berat' => 110,
            ],
            [
                'nama_produk' => 'Bangku kaki roda',
                'kategori' => 'Bangku',
                'jenis_kayu' => 'Kayu Jati',
                'harga' => 2500000,
                'deskripsi' => 'Bangku yang dihiasi dengan roda besar sebagai kaki bangku tersebut.',
                'berat' => 90,
            ],
        ];

        foreach ($products as $i => $product) {
            $sku = 'PRD-' . str_pad($i + 1, 3, '0', STR_PAD_LEFT);

            $productId = DB::table('products')->insertGetId([
                'nama_produk' => $product['nama_produk'],
                'kategori_id' => $categories[$product['kategori']],
                'jenis_kayu_id' => $woodTypes[$product['jenis_kayu']],
                'harga' => $product['harga'],
                'deskripsi' => $product['deskripsi'],
                'berat' => $product['berat'],
                'sku' => $sku,
                'stok' => rand(0, 10),
                'visibilitas' => 'aktif',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Insert Cloudinary image if mapping exists
            $namaProduk = $product['nama_produk'];
            if (isset($cloudinaryMap[$namaProduk])) {
                DB::table('product_images')->insert([
                    'product_id' => $productId,
                    'path' => $cloudinaryMap[$namaProduk],
                    'alt_text' => $namaProduk,
                    'urutan' => 0,
                    'is_cover' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
